x-base: &base
  restart: always

x-volumes: &volumes
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/hosts:/etc/hosts

x-networks: &networks
  networks:
    - default

services:

  mcpserver:
    <<: [*base, *volumes]
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        BASE_IMAGE: ${PYTHON_BASE_IMAGE}
    image: ${IMAGE_REGISTRY_NAME}/${IMAGE_NAME}:${VERSION}
    container_name: ${CONTAINER_NAME}_${VERSION}
    profiles:
      - all
    environment:
      MODE: keep
    volumes:
      - ./:/app
    ports:
      - "${EXPOSE_PORT}:8000"
